import { ok } from "node:assert";
import { describe, it } from "node:test";
import { resolvePath } from "@typespec/compiler";
import { createTester, resolveVirtualPath } from "@typespec/compiler/testing";

const EMITTER = "@massivescale/tsp-aspnetcore-api";

const tester = createTester(resolvePath(import.meta.dirname, "../.."), {
  libraries: [EMITTER, "@typespec/http", "@typespec/versioning"],
});

/** Absolute path of the emitter output directory inside the virtual file system. */
const OUTPUT_DIR = resolveVirtualPath(resolvePath("tsp-output", EMITTER));

/** Header carrying the `<auto-generated>` marker written by the default `file` template. */
const GENERATED_HEADER = `//-----------------------------------------------------------------------
// <copyright file="seed.g.cs" />
//
// This file is AUTO-GENERATED. Do not edit this file directly.
// <auto-generated />
//-----------------------------------------------------------------------
namespace Demo.Models { public partial class Seed { } }
`;

const MODEL = `
  namespace Demo;
  model User { id: string; }
`;

describe("csharp emitter - clean-output-dirs", () => {
  it("removes a stale generated file (marker present) before emitting", async () => {
    const instance = await tester.emit(EMITTER).createInstance();
    instance.fs.add(
      resolvePath(OUTPUT_DIR, "Models", "Stale.g.cs"),
      GENERATED_HEADER,
    );

    const [result] = await instance.compileAndDiagnose(MODEL);

    ok(
      result.outputs["Models/User.g.cs"],
      "expected the current model to be emitted",
    );
    ok(
      result.outputs["Models/Stale.g.cs"] === undefined,
      "stale generated file should have been removed before emit",
    );
  });

  it("leaves a non-generated file behind and warns when it lacks the marker", async () => {
    const instance = await tester.emit(EMITTER).createInstance();
    // Matches the generated extension but has no <auto-generated> marker.
    instance.fs.add(
      resolvePath(OUTPUT_DIR, "Models", "Handwritten.g.cs"),
      "namespace Demo.Models { public partial class Handwritten { } }\n",
    );
    // Does not match the generated extension at all.
    instance.fs.add(
      resolvePath(OUTPUT_DIR, "Models", "Keep.cs"),
      "namespace Demo.Models { public class Keep { } }\n",
    );

    const [result, diagnostics] = await instance.compileAndDiagnose(MODEL);

    ok(
      result.outputs["Models/Handwritten.g.cs"],
      "extension-matching file without marker must be left behind",
    );
    ok(
      result.outputs["Models/Keep.cs"],
      "non-generated-extension file must be left behind",
    );

    const warning = diagnostics.find(
      (d) => d.code === `${EMITTER}/output-file-left-behind`,
    );
    ok(
      warning,
      `expected output-file-left-behind warning, got: ${JSON.stringify(diagnostics)}`,
    );
    ok(
      warning.message.includes("Handwritten.g.cs"),
      `warning should name the retained file: ${warning.message}`,
    );
    // The plain `.cs` file is not a removal candidate, so it must not warn.
    ok(
      !warning.message.includes("Keep.cs"),
      `plain .cs files should not be reported: ${warning.message}`,
    );
  });

  it("does not touch the output directory when clean-output-dirs is false", async () => {
    const instance = await tester
      .emit(EMITTER, { "clean-output-dirs": false })
      .createInstance();
    instance.fs.add(
      resolvePath(OUTPUT_DIR, "Models", "Stale.g.cs"),
      GENERATED_HEADER,
    );

    const [result, diagnostics] = await instance.compileAndDiagnose(MODEL);

    ok(
      result.outputs["Models/Stale.g.cs"],
      "stale file must be preserved when cleaning is disabled",
    );
    ok(
      !diagnostics.some((d) => d.code === `${EMITTER}/output-file-left-behind`),
      "no left-behind warning should be emitted when cleaning is disabled",
    );
  });
});
