//-----------------------------------------------------------------------
// <copyright file="CustomersControllerBase.g.cs" />
//
// This file is AUTO-GENERATED. Do not edit this file directly.
// <auto-generated />
//-----------------------------------------------------------------------
#pragma warning disable CS1591 // Missing XML comment for publicly visible type or member
#pragma warning disable CS0612 // Type or member is obsolete
#nullable enable

using System;
using System.Collections.Generic;
using System.Threading;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;

namespace MarketOnce.Community.Campaign.Api.Controllers
{
    /// <summary>
    /// Controller for Customer entities.
    /// </summary>
    [ApiController]
    [System.Diagnostics.CodeAnalysis.ExcludeFromCodeCoverage]
    public abstract class CustomersControllerBase : ControllerBase
    {
        /// <summary>
        /// Retrieves a list of all customers.
        /// </summary>
        [HttpGet("/api/v1.0/customers")]
        [HttpGet("/api/v2.0/customers")]
        public abstract Task<IActionResult> List(CancellationToken cancellationToken);
    
        /// <summary>
        /// Retrieves a specific customer by their unique identifier.
        /// </summary>
        [HttpGet("/api/v1.0/customers/{id}")]
        [HttpGet("/api/v2.0/customers/{id}")]
        public abstract Task<IActionResult> Read([FromRoute] string id, CancellationToken cancellationToken);
    
        /// <summary>
        /// Creates a new customer with the provided information.
        /// </summary>
        [HttpPost("/api/v1.0/customers")]
        [HttpPost("/api/v2.0/customers")]
        public abstract Task<IActionResult> Create([FromBody] MarketOnce.Community.Campaign.Api.Models.Customer body, CancellationToken cancellationToken);
    
        /// <summary>
        /// Updates an existing customer with the provided information. Only the fields included in the request body will be updated.
        /// </summary>
        [HttpPatch("/api/v1.0/customers/{id}")]
        [HttpPatch("/api/v2.0/customers/{id}")]
        public abstract Task<IActionResult> Update([FromRoute] string id, [FromBody] MarketOnce.Community.Campaign.Api.Helpers.MergePatch<MarketOnce.Community.Campaign.Api.Models.Customer> body, CancellationToken cancellationToken);
    
        /// <summary>
        /// Deletes a customer by their unique identifier.
        /// </summary>
        [HttpDelete("/api/v1.0/customers/{id}")]
        public abstract Task<IActionResult> Delete([FromRoute] string id, CancellationToken cancellationToken);
    
    }

}

#pragma warning restore CS0612 // Type or member is obsolete
#pragma warning restore CS1591 // Missing XML comment for publicly visible type or member