//-----------------------------------------------------------------------
// <copyright file="PetsControllerBase.g.cs" />
//
// This file is AUTO-GENERATED. Do not edit this file directly.
// <auto-generated />
//-----------------------------------------------------------------------
#pragma warning disable CS1591 // Missing XML comment for publicly visible type or member
#pragma warning disable CS0612 // Type or member is obsolete
#nullable enable

using System;
using System.Collections.Generic;
using System.Threading;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;

namespace MarketOnce.Community.Campaign.Api.Controllers
{
    /// <summary>
    /// Controller for Pet entities within a Store.
    /// </summary>
    [ApiController]
    [System.Diagnostics.CodeAnalysis.ExcludeFromCodeCoverage]
    public abstract class PetsControllerBase : ControllerBase
    {
        /// <summary>
        /// Retrieves a list of all pets in the specified store.
        /// </summary>
        [HttpGet("/api/v1.0/{storeId}/pets")]
        [HttpGet("/api/v2.0/{storeId}/pets")]
        public abstract Task<IActionResult> List([FromRoute] string storeId, CancellationToken cancellationToken);
    
        /// <summary>
        /// Adds a new pet to the specified store.
        /// </summary>
        [HttpPost("/api/v1.0/{storeId}/pets")]
        [HttpPost("/api/v2.0/{storeId}/pets")]
        public abstract Task<IActionResult> Create([FromRoute] string storeId, [FromBody] MarketOnce.Community.Campaign.Api.Models.Pet body, CancellationToken cancellationToken);
    
        /// <summary>
        /// Updates an existing pet in the specified store. Only the fields included in the request body will be updated.
        /// </summary>
        [HttpPatch("/api/v2.0/{storeId}/pets/{petId}")]
        public abstract Task<IActionResult> Update([FromRoute] string storeId, [FromRoute] string petId, [FromBody] MarketOnce.Community.Campaign.Api.Helpers.MergePatch<MarketOnce.Community.Campaign.Api.Models.Pet> body, CancellationToken cancellationToken);
    
        /// <summary>
        /// Removes a pet from the specified store.
        /// </summary>
        [HttpDelete("/api/v2.0/{storeId}/pets/{petId}")]
        public abstract Task<IActionResult> Delete([FromRoute] string storeId, [FromRoute] string petId, CancellationToken cancellationToken);
    
    }

}

#pragma warning restore CS0612 // Type or member is obsolete
#pragma warning restore CS1591 // Missing XML comment for publicly visible type or member