//-----------------------------------------------------------------------
// <copyright file="IWidgetsService.g.cs" />
//
// This file is AUTO-GENERATED. Do not edit this file directly.
// <auto-generated />
//-----------------------------------------------------------------------
#pragma warning disable CS1591 // Missing XML comment for publicly visible type or member
#pragma warning disable CS0612 // Type or member is obsolete
#nullable enable

using System;
using System.Collections.Generic;
using System.Threading.Tasks;
using MassiveScale.Versioned.Api.Example.Models;

namespace MassiveScale.Versioned.Api.Example.Services
{
    public interface IWidgetsService
    {
        /// <summary>
        /// List widgets
        /// </summary>
        Task<WidgetList?> ListAsync();

        /// <summary>
        /// Read widgets
        /// </summary>
        Task<Widget?> ReadAsync(string id);

        /// <summary>
        /// Create a widget
        /// </summary>
        Task<Widget?> CreateAsync(Widget body);

        /// <summary>
        /// Update a widget
        /// </summary>
        Task UpdateAsync(string id, WidgetMergePatchUpdate body);

        /// <summary>
        /// Delete a widget
        /// </summary>
        Task DeleteAsync(string id);

        /// <summary>
        /// Analyze a widget
        /// </summary>
        Task<AnalyzeResult?> AnalyzeAsync(string id);


    }

}

#pragma warning restore CS0612 // Type or member is obsolete
#pragma warning restore CS1591 // Missing XML comment for publicly visible type or member