//-----------------------------------------------------------------------
// <copyright file="ICustomersService.g.cs" />
//
// This file is AUTO-GENERATED. Do not edit this file directly.
// <auto-generated />
//-----------------------------------------------------------------------
#pragma warning disable CS1591 // Missing XML comment for publicly visible type or member
#pragma warning disable CS0612 // Type or member is obsolete
#nullable enable

using System;
using System.Collections.Generic;
using System.Threading;
using System.Threading.Tasks;

namespace MarketOnce.Community.Campaign.Api.Services
{
    /// <summary>
    /// Controller for Customer entities.
    /// </summary>
    public partial interface ICustomersService
    {
        /// <summary>
        /// Retrieves a list of all customers.
        /// </summary>
        Task<IList<MarketOnce.Community.Campaign.Api.Models.Customer>?> ListAsync(CancellationToken cancellationToken);
    
        /// <summary>
        /// Retrieves a specific customer by their unique identifier.
        /// </summary>
        Task<MarketOnce.Community.Campaign.Api.Models.Customer?> ReadAsync(string id, CancellationToken cancellationToken);
    
        /// <summary>
        /// Creates a new customer with the provided information.
        /// </summary>
        Task<MarketOnce.Community.Campaign.Api.Models.Customer?> CreateAsync(MarketOnce.Community.Campaign.Api.Models.Customer body, CancellationToken cancellationToken);
    
        /// <summary>
        /// Updates an existing customer with the provided information. Only the fields included in the request body will be updated.
        /// </summary>
        Task<MarketOnce.Community.Campaign.Api.Models.Customer?> UpdateAsync(string id, MarketOnce.Community.Campaign.Api.Helpers.MergePatch<MarketOnce.Community.Campaign.Api.Models.Customer> body, CancellationToken cancellationToken);
    
        /// <summary>
        /// Deletes a customer by their unique identifier.
        /// </summary>
        Task DeleteAsync(string id, CancellationToken cancellationToken);
    
    
    }

}

#pragma warning restore CS0612 // Type or member is obsolete
#pragma warning restore CS1591 // Missing XML comment for publicly visible type or member