//-----------------------------------------------------------------------
// <copyright file="IPetsService.g.cs" />
//
// This file is AUTO-GENERATED. Do not edit this file directly.
// <auto-generated />
//-----------------------------------------------------------------------
#pragma warning disable CS1591 // Missing XML comment for publicly visible type or member
#pragma warning disable CS0612 // Type or member is obsolete
#nullable enable

using System;
using System.Collections.Generic;
using System.Threading;
using System.Threading.Tasks;
using MarketOnce.Community.Campaign.Api.Helpers;
using MarketOnce.Community.Campaign.Api.Models;

namespace MarketOnce.Community.Campaign.Api.Services
{
    /// <summary>
    /// Controller for Pet entities within a Store.
    /// </summary>
    public partial interface IPetsService
    {
        /// <summary>
        /// Retrieves a list of all pets in the specified store.
        /// </summary>
        Task<IList<Pet>?> ListAsync(string storeId, CancellationToken cancellationToken);
    
        /// <summary>
        /// Adds a new pet to the specified store.
        /// </summary>
        Task<Pet?> CreateAsync(string storeId, Pet body, CancellationToken cancellationToken);
    
        /// <summary>
        /// Updates an existing pet in the specified store. Only the fields included in the request body will be updated.
        /// </summary>
        Task<Pet?> UpdateAsync(string storeId, string petId, MergePatch<Pet> body, CancellationToken cancellationToken);
    
        /// <summary>
        /// Removes a pet from the specified store.
        /// </summary>
        Task DeleteAsync(string storeId, string petId, CancellationToken cancellationToken);
    
    
    }

}

#pragma warning restore CS0612 // Type or member is obsolete
#pragma warning restore CS1591 // Missing XML comment for publicly visible type or member