//-----------------------------------------------------------------------
// <copyright file="IStoresService.g.cs" />
//
// This file is AUTO-GENERATED. Do not edit this file directly.
// <auto-generated />
//-----------------------------------------------------------------------
#pragma warning disable CS1591 // Missing XML comment for publicly visible type or member
#pragma warning disable CS0612 // Type or member is obsolete
#nullable enable

using System;
using System.Collections.Generic;
using System.Threading;
using System.Threading.Tasks;

namespace MarketOnce.Community.Campaign.Api.Services
{
    /// <summary>
    /// Controller for Store entities.
    /// </summary>
    public partial interface IStoresService
    {
        /// <summary>
        /// Retrieves a list of all stores.
        /// </summary>
        Task<MarketOnce.Community.Campaign.Api.Models.PagedResult?> ListAsync(CancellationToken cancellationToken);
    
        /// <summary>
        /// Retrieves a specific store by its unique identifier.
        /// </summary>
        Task<MarketOnce.Community.Campaign.Api.Models.Store?> ReadAsync(string id, CancellationToken cancellationToken);
    
        /// <summary>
        /// Creates a new store with the provided information.
        /// </summary>
        Task<MarketOnce.Community.Campaign.Api.Models.Store?> CreateAsync(MarketOnce.Community.Campaign.Api.Models.Store body, CancellationToken cancellationToken);
    
        /// <summary>
        /// Updates an existing store with the provided information. Only the fields included in the request body will be updated.
        /// </summary>
        Task UpdateAsync(string id, MarketOnce.Community.Campaign.Api.Helpers.MergePatch<MarketOnce.Community.Campaign.Api.Models.Store> body, CancellationToken cancellationToken);
    
        /// <summary>
        /// Deletes a store by its unique identifier.
        /// </summary>
        Task DeleteAsync(string id, CancellationToken cancellationToken);
    
    
    }

}

#pragma warning restore CS0612 // Type or member is obsolete
#pragma warning restore CS1591 // Missing XML comment for publicly visible type or member