//-----------------------------------------------------------------------
// <copyright file="WidgetMergePatchUpdate.g.cs" />
//
// This file is AUTO-GENERATED. Do not edit this file directly.
// <auto-generated />
//-----------------------------------------------------------------------
#pragma warning disable CS1591 // Missing XML comment for publicly visible type or member
#pragma warning disable CS0612 // Type or member is obsolete
#nullable enable

using System;
using System.Collections.Generic;
using System.Text.Json.Serialization;
using MassiveScale.Simple.Api.Example.Helpers;
namespace MassiveScale.Simple.Api.Example
{
    public partial class WidgetMergePatchUpdate : IWidgetMergePatchUpdate
    {
        [JsonPropertyName("id")]
        public MergePatchValue<string?> Id { get; set; } = MergePatchValue<string?>.Absent;

        [JsonPropertyName("weight")]
        public MergePatchValue<int?> Weight { get; set; } = MergePatchValue<int?>.Absent;

        /// <summary>
        /// The widget color.
        /// </summary>
        [JsonPropertyName("color")]
        public MergePatchValue<WidgetColor?> Color { get; set; } = MergePatchValue<WidgetColor?>.Absent;

    }

}

#pragma warning restore CS0612 // Type or member is obsolete
#pragma warning restore CS1591 // Missing XML comment for publicly visible type or member