//-----------------------------------------------------------------------
// <copyright file="IAnalyzeResult.g.cs" />
//
// This file is AUTO-GENERATED. Do not edit this file directly.
// <auto-generated />
//-----------------------------------------------------------------------
#pragma warning disable CS1591 // Missing XML comment for publicly visible type or member
#pragma warning disable CS0612 // Type or member is obsolete
#nullable enable

using System;
using System.Collections.Generic;
using System.Text.Json.Serialization;

namespace MassiveScale.Versioned.Api.Example.Models
{
    public partial interface IAnalyzeResult
    {
        [JsonPropertyName("id")]
        [JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingNull)]
        string? Id { get; set; }

        [JsonPropertyName("analysis")]
        [JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingNull)]
        string? Analysis { get; set; }

    }

}

#pragma warning restore CS0612 // Type or member is obsolete
#pragma warning restore CS1591 // Missing XML comment for publicly visible type or member