//-----------------------------------------------------------------------
// <copyright file="WidgetColor.g.cs" />
//
// This file is AUTO-GENERATED. Do not edit this file directly.
// <auto-generated />
//-----------------------------------------------------------------------
#pragma warning disable CS1591 // Missing XML comment for publicly visible type or member
#pragma warning disable CS0612 // Type or member is obsolete
#nullable enable

using System;
using System.Collections.Generic;
using System.Runtime.Serialization;
using System.Text.Json.Serialization;
using MassiveScale.Versioned.Api.Example.Helpers;

namespace MassiveScale.Versioned.Api.Example.Models
{
    [JsonConverter(typeof(EnumMemberConverterFactory))]
    public enum WidgetColor
    {
        [EnumMember(Value = "red")]
        Red,
        [EnumMember(Value = "blue")]
        Blue
    }

}

#pragma warning restore CS0612 // Type or member is obsolete
#pragma warning restore CS1591 // Missing XML comment for publicly visible type or member