//-----------------------------------------------------------------------
// <copyright file="WidgetMergePatchUpdate.g.cs" />
//
// This file is AUTO-GENERATED. Do not edit this file directly.
// <auto-generated />
//-----------------------------------------------------------------------
#pragma warning disable CS1591 // Missing XML comment for publicly visible type or member
#pragma warning disable CS0612 // Type or member is obsolete
#nullable enable

using System;
using System.Collections.Generic;
using System.Text.Json.Serialization;
using MassiveScale.Versioned.Api.Example.Helpers;

namespace MassiveScale.Versioned.Api.Example.Models
{
    public partial class WidgetMergePatchUpdate : IWidgetMergePatchUpdate
    {
        [JsonPropertyName("id")]
        public MergePatchValue<string?> Id { get; set; } = MergePatchValue<string?>.Absent;
    
        [JsonPropertyName("weight")]
        public MergePatchValue<int?> Weight { get; set; } = MergePatchValue<int?>.Absent;
    
        [JsonPropertyName("color")]
        public MergePatchValue<object?> Color { get; set; } = MergePatchValue<object?>.Absent;
    
    }

}

#pragma warning restore CS0612 // Type or member is obsolete
#pragma warning restore CS1591 // Missing XML comment for publicly visible type or member