//-----------------------------------------------------------------------
// <copyright file="MergePatch.g.cs" />
//
// This file is AUTO-GENERATED. Do not edit this file directly.
// <auto-generated />
//-----------------------------------------------------------------------
#pragma warning disable CS1591 // Missing XML comment for publicly visible type or member
#pragma warning disable CS0612 // Type or member is obsolete
#nullable enable

using System;
using System.Collections.Generic;
using System.Reflection;
using System.Text.Json;
using System.Text.Json.Serialization;
using System.Threading;
using System.Threading.Tasks;

namespace MarketOnce.Community.Campaign.Api.Helpers
{
    /// <summary>
    /// Generic RFC 7396 JSON Merge Patch container.
    /// Captures all properties sent by the client; use <see cref="IsDefined"/> to
    /// distinguish "field absent from the request" from "field explicitly set to null".
    /// </summary>
    /// <typeparam name="T">The entity type this patch targets.</typeparam>
    [System.Diagnostics.CodeAnalysis.ExcludeFromCodeCoverage]
    public class MergePatch<T>
    {
        private static readonly PropertyInfo[] _typeProperties =
            typeof(T).GetProperties(BindingFlags.Public | BindingFlags.Instance);
    
        /// <summary>
        /// Raw JSON properties received in the patch payload, keyed by property name.
        /// Populated automatically by <c>System.Text.Json</c> via <c>[JsonExtensionData]</c>.
        /// </summary>
        [JsonExtensionData]
        public Dictionary<string, JsonElement> Properties { get; init; } = new(StringComparer.OrdinalIgnoreCase);
    
        /// <summary>
        /// Returns <see langword="true"/> if <paramref name="propertyName"/> was explicitly
        /// included in the patch payload (even if its value is <see langword="null"/>).
        /// </summary>
        public bool IsDefined(string propertyName) =>
            Properties.ContainsKey(propertyName);
    
        /// <summary>
        /// Returns <see langword="true"/> if <paramref name="propertyName"/> is present in the
        /// patch and its JSON value is <c>null</c> (RFC 7396 "clear field" signal).
        /// </summary>
        public bool IsNull(string propertyName) =>
            Properties.TryGetValue(propertyName, out var el) && el.ValueKind == JsonValueKind.Null;
    
        /// <summary>
        /// Returns the string value of <paramref name="propertyName"/>, or
        /// <see langword="null"/> when the property is absent or its JSON value is null.
        /// </summary>
        public string? GetString(string propertyName)
        {
            if (!Properties.TryGetValue(propertyName, out var element)) return null;
            if (element.ValueKind == JsonValueKind.Null) return null;
            return element.ValueKind == JsonValueKind.String ? element.GetString() : element.ToString();
        }
    
        /// <summary>
        /// Attempts to deserialize <paramref name="propertyName"/> to <typeparamref name="TValue"/>.
        /// Returns <see langword="true"/> when the property is present (even if null);
        /// <see langword="false"/> when it is absent or cannot be deserialized.
        /// </summary>
        public bool TryGetValue<TValue>(string propertyName, out TValue? value, JsonSerializerOptions? options = null)
        {
            value = default;
            if (!Properties.TryGetValue(propertyName, out var element)) return false;
            if (element.ValueKind == JsonValueKind.Null) return true;
            try
            {
                value = JsonSerializer.Deserialize<TValue>(element.GetRawText(), options);
                return true;
            }
            catch
            {
                return false;
            }
        }
    
        /// <summary>Returns the names of all properties explicitly provided in this patch.</summary>
        public IEnumerable<string> DefinedProperties => Properties.Keys;
    
        /// <summary>
        /// Returns the names of all properties that have been modified (i.e. explicitly
        /// provided) in this patch.
        /// </summary>
        public IEnumerable<string> GetChangedPropertyNames() => Properties.Keys;
    
        /// <summary>
        /// Attempts to get the declared <see cref="Type"/> of the property named
        /// <paramref name="name"/> on <typeparamref name="T"/>.
        /// Returns <see langword="false"/> when no matching public instance property exists.
        /// </summary>
        public bool TryGetPropertyType(string name, out Type? type)
        {
            var prop = FindProperty(name);
            type = prop?.PropertyType;
            return prop is not null;
        }
    
        /// <summary>
        /// Attempts to get the patch value for the property named <paramref name="name"/>,
        /// deserialized to the declared property type on <typeparamref name="T"/>.
        /// Returns <see langword="false"/> when the property is absent from the patch,
        /// <typeparamref name="T"/> declares no such property, or deserialization fails.
        /// </summary>
        public bool TryGetPropertyValue(string name, out object? value, JsonSerializerOptions? options = null)
        {
            value = null;
            if (!Properties.TryGetValue(name, out var element)) return false;
            var prop = FindProperty(name);
            if (prop is null) return false;
            if (element.ValueKind == JsonValueKind.Null) return true;
            try
            {
                value = JsonSerializer.Deserialize(element.GetRawText(), prop.PropertyType, options);
                return true;
            }
            catch
            {
                return false;
            }
        }
    
        /// <summary>
        /// Serializes <paramref name="value"/> and stores it as a patch entry for the
        /// property named <paramref name="name"/>. Pass <see langword="null"/> to mark
        /// the field for clearing (RFC 7396 semantics).
        /// Returns <see langword="false"/> when serialization fails.
        /// </summary>
        public bool TrySetPropertyValue(string name, object? value, JsonSerializerOptions? options = null)
        {
            try
            {
                using var doc = JsonDocument.Parse(JsonSerializer.Serialize(value, options));
                Properties[name] = doc.RootElement.Clone();
                return true;
            }
            catch
            {
                return false;
            }
        }
    
        /// <summary>
        /// Constructs a <see cref="MergePatch{T}"/> from a JSON string, treating every
        /// property present in the JSON as explicitly defined in the patch.
        /// </summary>
        /// <remarks>
        /// Properties are keyed by their JSON wire names. If <typeparamref name="T"/> uses
        /// <c>[JsonPropertyName]</c> attributes or a custom <see cref="JsonSerializerOptions"/>
        /// naming policy, the keys in <see cref="Properties"/> will reflect those wire names
        /// and may not match C# property names used by <see cref="Patch(T, JsonSerializerOptions?)"/>.
        /// </remarks>
        public static MergePatch<T> FromJson(string json, JsonSerializerOptions? options = null) =>
            JsonSerializer.Deserialize<MergePatch<T>>(json, options) ?? new MergePatch<T>();
    
        /// <summary>
        /// Constructs a <see cref="MergePatch{T}"/> from an existing <typeparamref name="T"/>
        /// instance by serializing it to JSON. Every property that is included in the serialized
        /// output is treated as explicitly defined in the patch.
        /// </summary>
        /// <remarks>
        /// Serialization honours <paramref name="options"/> (including
        /// <c>DefaultIgnoreCondition</c>). Pass <see langword="null"/> options to include all
        /// properties, even those with <see langword="null"/> values.
        /// </remarks>
        public static MergePatch<T> From(T entity, JsonSerializerOptions? options = null) =>
            FromJson(JsonSerializer.Serialize(entity, options), options);
    
        /// <summary>
        /// Applies all properties defined in this patch to <paramref name="original"/> using
        /// reflection. Each defined property is deserialized to the target property's declared
        /// type and written back. Properties absent from <typeparamref name="T"/>, that cannot
        /// be deserialized, or that are read-only are silently skipped.
        /// </summary>
        public void Patch(T original, JsonSerializerOptions? options = null)
        {
            if (original is null) return;
            foreach (var (name, element) in Properties)
            {
                var prop = FindProperty(name);
                if (prop is null || !prop.CanWrite) continue;
                try
                {
                    object? value = element.ValueKind == JsonValueKind.Null
                        ? null
                        : JsonSerializer.Deserialize(element.GetRawText(), prop.PropertyType, options);
                    prop.SetValue(original, value);
                }
                catch { }
            }
        }
    
        /// <summary>
        /// Asynchronous variant of <see cref="Patch(T, JsonSerializerOptions?)"/>.
        /// Applies all properties defined in this patch to <paramref name="original"/> using
        /// reflection, then returns a completed <see cref="ValueTask"/>.
        /// Throws <see cref="OperationCanceledException"/> if <paramref name="cancellationToken"/>
        /// is already cancelled before work begins.
        /// </summary>
        public ValueTask PatchAsync(T original, JsonSerializerOptions? options = null, CancellationToken cancellationToken = default)
        {
            cancellationToken.ThrowIfCancellationRequested();
            Patch(original, options);
            return ValueTask.CompletedTask;
        }
    
        private static PropertyInfo? FindProperty(string name) =>
            Array.Find(_typeProperties, p =>
            {
                var wireName = p.GetCustomAttribute<JsonPropertyNameAttribute>()?.Name ?? p.Name;
                return string.Equals(wireName, name, StringComparison.OrdinalIgnoreCase);
            });
    }

}

#pragma warning restore CS0612 // Type or member is obsolete
#pragma warning restore CS1591 // Missing XML comment for publicly visible type or member