//-----------------------------------------------------------------------
// <copyright file="EnumMemberConverter.g.cs" />
//
// This file is AUTO-GENERATED. Do not edit this file directly.
// <auto-generated />
//-----------------------------------------------------------------------
#pragma warning disable CS1591 // Missing XML comment for publicly visible type or member
#pragma warning disable CS0612 // Type or member is obsolete
#nullable enable

using System;
using System.Collections.Generic;
using System.Reflection;
using System.Runtime.Serialization;
using System.Text.Json;
using System.Text.Json.Serialization;
namespace MassiveScale.Simple.Api.Example.Helpers
{
    /// <summary>
    /// Creates <see cref="EnumMemberConverter{T}"/> instances for any enum type at runtime.
    /// </summary>
    internal sealed class EnumMemberConverterFactory : JsonConverterFactory
    {
        /// <inheritdoc />
        public override bool CanConvert(Type typeToConvert) =>
            typeToConvert.IsEnum;
    
        /// <inheritdoc />
        public override JsonConverter? CreateConverter(Type typeToConvert, JsonSerializerOptions options) =>
            (JsonConverter)Activator.CreateInstance(
                typeof(EnumMemberConverter<>).MakeGenericType(typeToConvert))!;
    }
    
    /// <summary>
    /// A <see cref="JsonConverter{T}"/> that serializes enum values using the
    /// string declared in each member's <see cref="EnumMemberAttribute"/>.
    /// When no attribute is present the field name is used as the wire value.
    /// Deserialization is case-insensitive.
    /// </summary>
    /// <typeparam name="T">The enum type to convert.</typeparam>
    internal sealed class EnumMemberConverter<T> : JsonConverter<T> where T : struct, Enum
    {
        /// <summary>
        /// Maps wire names (case-insensitive) to their corresponding enum members. Built once per <typeparamref name="T"/>.
        /// </summary>
        private static readonly Dictionary<string, T> _readMap;
    
        /// <summary>
        /// Maps enum members to their wire names. Built once per <typeparamref name="T"/>.
        /// </summary>
        private static readonly Dictionary<T, string> _writeMap;
    
        /// <summary>
        /// Initializes the read and write maps by reflecting over all public static fields of <typeparamref name="T"/>.
        /// </summary>
        static EnumMemberConverter()
        {
            _readMap = new(StringComparer.OrdinalIgnoreCase);
            _writeMap = new();
    
            foreach (var field in typeof(T).GetFields(BindingFlags.Public | BindingFlags.Static))
            {
                var attr = field.GetCustomAttribute<EnumMemberAttribute>();
                var wireName = attr?.Value ?? field.Name;
                var value = (T)field.GetValue(null)!;
                _readMap[wireName] = value;
                _writeMap[value] = wireName;
            }
        }
    
        /// <inheritdoc />
        public override T Read(
            ref Utf8JsonReader reader, Type typeToConvert, JsonSerializerOptions options)
        {
            var s = reader.GetString()
                ?? throw new JsonException($"Expected a string value for {typeof(T).Name}.");
    
            if (_readMap.TryGetValue(s, out var value)) return value;
    
            throw new JsonException($"Unknown value '{s}' for {typeof(T).Name}.");
        }
    
        /// <inheritdoc />
        public override void Write(
            Utf8JsonWriter writer, T value, JsonSerializerOptions options)
        {
            if (_writeMap.TryGetValue(value, out var wireName))
                writer.WriteStringValue(wireName);
            else
                throw new JsonException($"Unknown enum value '{value}' for {typeof(T).Name}.");
        }
    }
}

#pragma warning restore CS0612 // Type or member is obsolete
#pragma warning restore CS1591 // Missing XML comment for publicly visible type or member