//-----------------------------------------------------------------------
// <copyright file="MergePatchValue.g.cs" />
//
// This file is AUTO-GENERATED. Do not edit this file directly.
// <auto-generated />
//-----------------------------------------------------------------------
#pragma warning disable CS1591 // Missing XML comment for publicly visible type or member
#pragma warning disable CS0612 // Type or member is obsolete
#nullable enable

using System;
using System.Text.Json;
using System.Text.Json.Serialization;

namespace MassiveScale.Simple.Api.Example.Helpers
{
    /// <summary>
    /// Represents an optional value in a JSON Merge Patch (RFC 7396) operation.
    /// Distinguishes between a field that is explicitly set (including to <see langword="null"/>)
    /// and a field that is absent from the patch payload.
    /// </summary>
    /// <typeparam name="T">The type of the wrapped value.</typeparam>
    [JsonConverter(typeof(MergePatchValueJsonConverterFactory))]
    public sealed class MergePatchValue<T>
    {
        /// <summary>Initializes a new instance with the given value and presence flag.</summary>
        /// <param name="value">The underlying value.</param>
        /// <param name="isPresent"><see langword="true"/> if the field was present in the payload; otherwise <see langword="false"/>.</param>
        private MergePatchValue(T? value, bool isPresent)
        {
            Value = value;
            IsPresent = isPresent;
        }

        /// <summary>
        /// Gets a sentinel that represents an absent (omitted) field.
        /// </summary>
        public static MergePatchValue<T> Absent { get; } = new(default, false);

        /// <summary>
        /// Gets the wrapped value, or <see langword="default"/> when the field is absent.
        /// </summary>
        public T? Value { get; }

        /// <summary>
        /// Gets a value indicating whether the field was present in the patch payload.
        /// </summary>
        public bool IsPresent { get; }

        /// <summary>
        /// Creates a present <see cref="MergePatchValue{T}"/> wrapping <paramref name="value"/>.
        /// </summary>
        /// <param name="value">The value to wrap.</param>
        public static MergePatchValue<T> Of(T? value) => new(value, true);

        /// <summary>
        /// Implicitly wraps <paramref name="value"/> as a present <see cref="MergePatchValue{T}"/>.
        /// </summary>
        /// <param name="value">The value to wrap.</param>
        public static implicit operator MergePatchValue<T>(T value) => Of(value);
    }

    /// <summary>
    /// Creates <see cref="MergePatchValueJsonConverter{T}"/> instances for any closed
    /// <see cref="MergePatchValue{T}"/> type at runtime.
    /// </summary>
    internal sealed class MergePatchValueJsonConverterFactory : JsonConverterFactory
    {
        /// <inheritdoc/>
        public override bool CanConvert(Type typeToConvert) =>
            typeToConvert.IsGenericType &&
            typeToConvert.GetGenericTypeDefinition() == typeof(MergePatchValue<>);

        /// <inheritdoc/>
        public override JsonConverter? CreateConverter(Type typeToConvert, JsonSerializerOptions options)
        {
            Type valueType = typeToConvert.GetGenericArguments()[0];
            return (JsonConverter)Activator.CreateInstance(
                typeof(MergePatchValueJsonConverter<>).MakeGenericType(valueType))!;
        }
    }

    /// <summary>
    /// Reads and writes <see cref="MergePatchValue{T}"/> as its underlying <typeparamref name="T"/> value.
    /// Absent fields are never written; present fields (including explicit <see langword="null"/>) are written normally.
    /// </summary>
    /// <typeparam name="T">The type of the wrapped value.</typeparam>
    internal sealed class MergePatchValueJsonConverter<T> : JsonConverter<MergePatchValue<T>>
    {
        /// <inheritdoc/>
        public override MergePatchValue<T> Read(
            ref Utf8JsonReader reader, Type typeToConvert, JsonSerializerOptions options) =>
            MergePatchValue<T>.Of(JsonSerializer.Deserialize<T>(ref reader, options));

        /// <inheritdoc/>
        public override void Write(
            Utf8JsonWriter writer, MergePatchValue<T> value, JsonSerializerOptions options)
        {
            if (!value.IsPresent) return;
            JsonSerializer.Serialize(writer, value.Value, options);
        }
    }

}

#pragma warning restore CS0612 // Type or member is obsolete
#pragma warning restore CS1591 // Missing XML comment for publicly visible type or member