//-----------------------------------------------------------------------
// <copyright file="EntityBase.g.cs" />
//
// This file is AUTO-GENERATED. Do not edit this file directly.
// <auto-generated />
//-----------------------------------------------------------------------
#pragma warning disable CS1591 // Missing XML comment for publicly visible type or member
#pragma warning disable CS0612 // Type or member is obsolete
#nullable enable

using System;
using System.Collections.Generic;
using System.Text.Json.Serialization;

namespace MarketOnce.Community.Campaign.Api.Models
{
    /// <summary>
    /// Base model for all entities in the API.
    /// </summary>
    [System.Diagnostics.CodeAnalysis.ExcludeFromCodeCoverage]
    public partial class EntityBase
    {
        /// <summary>
        /// Unique identifier of the entity.
        /// </summary>
        [JsonPropertyName("id")]
        [JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingNull)]
        public Guid? Id { get; set; }
    
        /// <summary>
        /// Date and time when the resource was created.
        /// </summary>
        [JsonPropertyName("createdDateTime")]
        [JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingNull)]
        public DateTimeOffset? CreatedDateTime { get; set; }
    
        /// <summary>
        /// Date and time when the resource was last modified.
        /// </summary>
        [JsonPropertyName("lastModifiedDateTime")]
        [JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingNull)]
        public DateTimeOffset? LastModifiedDateTime { get; set; }
    
    }

}

#pragma warning restore CS0612 // Type or member is obsolete
#pragma warning restore CS1591 // Missing XML comment for publicly visible type or member