//-----------------------------------------------------------------------
// <copyright file="ErrorResponseBase.g.cs" />
//
// This file is AUTO-GENERATED. Do not edit this file directly.
// <auto-generated />
//-----------------------------------------------------------------------
#pragma warning disable CS1591 // Missing XML comment for publicly visible type or member
#pragma warning disable CS0612 // Type or member is obsolete
#nullable enable

using System;
using System.Collections.Generic;
using System.Text.Json.Serialization;

namespace MarketOnce.Community.Campaign.Api.Models
{
    /// <summary>
    /// Represents an error response from the API.
    /// </summary>
    [System.Diagnostics.CodeAnalysis.ExcludeFromCodeCoverage]
    public partial class ErrorResponseBase
    {
        /// <summary>
        /// The HTTP status of the error response. e.g. badRequest, notFound, internalServerError, etc.
        /// </summary>
        [JsonPropertyName("code")]
        [JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingNull)]
        public string? Code { get; set; }
    
        /// <summary>
        /// A human-readable message describing the error.
        /// </summary>
        [JsonPropertyName("message")]
        [JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingNull)]
        public string? Message { get; set; }
    
        /// <summary>
        /// Correlation id for the request that resulted in the error.
        /// </summary>
        [JsonPropertyName("trace")]
        [JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingNull)]
        public string? correlationId { get; set; }
    
        /// <summary>
        /// An optional array of inner errors that provide more details about the error.
        /// </summary>
        [JsonPropertyName("innererror")]
        [JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingNull)]
        public IList<MarketOnce.Community.Campaign.Api.Models.ErrorResponseBase>? Innererror { get; set; }
    
    }

}

#pragma warning restore CS0612 // Type or member is obsolete
#pragma warning restore CS1591 // Missing XML comment for publicly visible type or member