//-----------------------------------------------------------------------
// <copyright file="Order.g.cs" />
//
// This file is AUTO-GENERATED. Do not edit this file directly.
// <auto-generated />
//-----------------------------------------------------------------------
#pragma warning disable CS1591 // Missing XML comment for publicly visible type or member
#pragma warning disable CS0612 // Type or member is obsolete
#nullable enable

using System;
using System.Collections.Generic;
using System.Text.Json.Serialization;

namespace MarketOnce.Community.Campaign.Api.Models
{
    /// <summary>
    /// Represents an order placed by a customer for one or more pets.
    /// </summary>
    [System.Diagnostics.CodeAnalysis.ExcludeFromCodeCoverage]
    public partial class Order : MarketOnce.Community.Campaign.Api.Models.EntityBase
    {
        /// <summary>
        /// The ID of the customer placing the order.
        /// </summary>
        [JsonPropertyName("customerId")]
        [JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingNull)]
        public Guid? CustomerId { get; set; }
    
        /// <summary>
        /// The list of items in the order.
        /// </summary>
        [JsonPropertyName("items")]
        [JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingNull)]
        public IList<MarketOnce.Community.Campaign.Api.Models.OrderItem>? Items { get; set; }
    
        /// <summary>
        /// The status of the order, e.g. placed, approved, delivered.
        /// </summary>
        [JsonPropertyName("status")]
        [JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingNull)]
        public MarketOnce.Community.Campaign.Api.Models.OrderStatus? Status { get; set; } = MarketOnce.Community.Campaign.Api.Models.OrderStatus.Placed;
    
    }

}

#pragma warning restore CS0612 // Type or member is obsolete
#pragma warning restore CS1591 // Missing XML comment for publicly visible type or member