//-----------------------------------------------------------------------
// <copyright file="PagedResult.g.cs" />
//
// This file is AUTO-GENERATED. Do not edit this file directly.
// <auto-generated />
//-----------------------------------------------------------------------
#pragma warning disable CS1591 // Missing XML comment for publicly visible type or member
#pragma warning disable CS0612 // Type or member is obsolete
#nullable enable

using System;
using System.Collections.Generic;
using System.Text.Json.Serialization;

namespace MarketOnce.Community.Campaign.Api.Models
{
    /// <summary>
    /// Model template for paginated results from the API.
    /// This is not intended to be used directly, but rather to be extended
    /// by specific models for paginated results using the pattern `model XList is PagedResult<X>`.
    /// </summary>
    [System.Diagnostics.CodeAnalysis.ExcludeFromCodeCoverage]
    public partial class PagedResult
    {
        /// <summary>
        /// The collection of items in the current page of results.
        /// </summary>
        [JsonPropertyName("items")]
        [JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingNull)]
        public IList<MarketOnce.Community.Campaign.Api.Models.Store>? Items { get; set; }
    
        /// <summary>
        /// The total count of items in the collection, if known.
        /// </summary>
        [JsonPropertyName("totalCount")]
        [JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingNull)]
        public int? TotalCount { get; set; }
    
    }

}

#pragma warning restore CS0612 // Type or member is obsolete
#pragma warning restore CS1591 // Missing XML comment for publicly visible type or member