//-----------------------------------------------------------------------
// <copyright file="Pet.g.cs" />
//
// This file is AUTO-GENERATED. Do not edit this file directly.
// <auto-generated />
//-----------------------------------------------------------------------
#pragma warning disable CS1591 // Missing XML comment for publicly visible type or member
#pragma warning disable CS0612 // Type or member is obsolete
#nullable enable

using System;
using System.Collections.Generic;
using System.Text.Json.Serialization;

namespace MarketOnce.Community.Campaign.Api.Models
{
    /// <summary>
    /// Represents a pet in the pet store.
    /// </summary>
    [JsonPolymorphic(TypeDiscriminatorPropertyName = "$type")]
    [JsonDerivedType(typeof(MarketOnce.Community.Campaign.Api.Models.Cat), "cat")]
    [JsonDerivedType(typeof(MarketOnce.Community.Campaign.Api.Models.Dog), "dog")]
    [System.Diagnostics.CodeAnalysis.ExcludeFromCodeCoverage]
    public abstract partial class Pet
    {
        /// <summary>
        /// Unique identifier of the entity.
        /// </summary>
        [JsonPropertyName("id")]
        [JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingNull)]
        public Guid? Id { get; set; }
    
        /// <summary>
        /// Date and time when the resource was created.
        /// </summary>
        [JsonPropertyName("createdDateTime")]
        [JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingNull)]
        public DateTimeOffset? CreatedDateTime { get; set; }
    
        /// <summary>
        /// Date and time when the resource was last modified.
        /// </summary>
        [JsonPropertyName("lastModifiedDateTime")]
        [JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingNull)]
        public DateTimeOffset? LastModifiedDateTime { get; set; }
    
        /// <summary>
        /// The name of the pet.
        /// </summary>
        [JsonPropertyName("name")]
        [JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingNull)]
        public string? Name { get; set; } = "Unnamed Pet";
    
        /// <summary>
        /// A list of photo URLs for the pet.
        /// </summary>
        [JsonPropertyName("photoUrls")]
        [JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingNull)]
        public IList<string>? PhotoUrls { get; set; }
    
        /// <summary>
        /// A list of tags associated with the pet.
        /// </summary>
        [JsonPropertyName("tags")]
        [JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingNull)]
        public IList<MarketOnce.Community.Campaign.Api.Models.Tag>? Tags { get; set; }
    
        /// <summary>
        /// The status of the pet in the store, e.g. available, pending, sold.
        /// </summary>
        [JsonPropertyName("status")]
        [JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingNull)]
        public MarketOnce.Community.Campaign.Api.Models.PetStatus? Status { get; set; } = MarketOnce.Community.Campaign.Api.Models.PetStatus.Available;
    
    }

}

#pragma warning restore CS0612 // Type or member is obsolete
#pragma warning restore CS1591 // Missing XML comment for publicly visible type or member