//-----------------------------------------------------------------------
// <copyright file="PetKind.g.cs" />
//
// This file is AUTO-GENERATED. Do not edit this file directly.
// <auto-generated />
//-----------------------------------------------------------------------
#pragma warning disable CS1591 // Missing XML comment for publicly visible type or member
#pragma warning disable CS0612 // Type or member is obsolete
#nullable enable

using System;
using System.Collections.Generic;
using System.Runtime.Serialization;
using System.Text.Json.Serialization;
using MarketOnce.Community.Campaign.Api.Helpers;

namespace MarketOnce.Community.Campaign.Api.Models
{
    /// <summary>
    /// Represents the category of a pet, e.g. dog, cat, fish, etc.
    /// </summary>
    [JsonConverter(typeof(EnumMemberConverterFactory))]
    public enum PetKind
    {
        [EnumMember(Value = "dog")]
        Dog,
        [EnumMember(Value = "cat")]
        Cat,
        [EnumMember(Value = "fish")]
        Fish,
        [EnumMember(Value = "bird")]
        Bird,
        [EnumMember(Value = "reptile")]
        Reptile
    }

}

#pragma warning restore CS0612 // Type or member is obsolete
#pragma warning restore CS1591 // Missing XML comment for publicly visible type or member