//-----------------------------------------------------------------------
// <copyright file="IWidgetMergePatchUpdate.g.cs" />
//
// This file is AUTO-GENERATED. Do not edit this file directly.
// <auto-generated />
//-----------------------------------------------------------------------
#pragma warning disable CS1591 // Missing XML comment for publicly visible type or member
#pragma warning disable CS0612 // Type or member is obsolete
#nullable enable

using System;
using System.Collections.Generic;
using System.Text.Json.Serialization;
using MassiveScale.Simple.Api.Example.Helpers;

namespace MassiveScale.Simple.Api.Example
{
    public partial interface IWidgetMergePatchUpdate
    {
        [JsonPropertyName("id")]
        MergePatchValue<string?> Id { get; set; }

        [JsonPropertyName("weight")]
        MergePatchValue<int?> Weight { get; set; }

        /// <summary>
        /// The widget color.
        /// </summary>
        [JsonPropertyName("color")]
        MergePatchValue<WidgetColor?> Color { get; set; }

    }

}

#pragma warning restore CS0612 // Type or member is obsolete
#pragma warning restore CS1591 // Missing XML comment for publicly visible type or member