// <auto-generated/>
// This file was auto-generated by @massivescale/tsp-aspnetcore-api. Do not edit manually.

#pragma warning disable CS1591 // Missing XML comment for publicly visible type or member
#pragma warning disable CS0612 // Type or member is obsolete
#pragma warning disable CS0618 // Type or member is obsolete
#nullable enable

using FluentValidation;
using Microsoft.AspNetCore.Http;

namespace MarketOnce.Community.Campaign.Api.Validators;

/// <summary>
/// Auto-generated version-aware POST validator for Customer.
/// Rules are applied based on the API version resolved from the inbound HTTP request
/// (URL segment, <c>api-version</c> header, or <c>api-version</c> query parameter).
/// Extend this partial class to add custom validation rules.
/// </summary>
[System.Diagnostics.CodeAnalysis.ExcludeFromCodeCoverage]
public partial class CustomerValidator : AbstractValidator<MarketOnce.Community.Campaign.Api.Models.Customer>
{
    private static readonly string[] _versions = new[] { "v1.0", "v2.0" };

    /// <summary>
    /// Initializes a new instance of <see cref="CustomerValidator"/> with version-aware auto-generated rules.
    /// </summary>
    public CustomerValidator(IHttpContextAccessor httpContextAccessor)
    {
        var _apiVersion = ResolveApiVersion(httpContextAccessor.HttpContext, "v1.0");

        // FirstName is required
        RuleFor(x => x.FirstName).NotEmpty();

        // FirstName cannot exceed a MaxLength of 100
        RuleFor(x => x.FirstName).MaximumLength(100);

        // LastName is required
        RuleFor(x => x.LastName).NotEmpty();

        // LastName cannot exceed a MaxLength of 100
        RuleFor(x => x.LastName).MaximumLength(100);

        // Email cannot exceed a MaxLength of 255
        RuleFor(x => x.Email).MaximumLength(255);

        // Email must be a valid email address
        RuleFor(x => x.Email).EmailAddress();

        // PhoneNumber cannot exceed a MaxLength of 20
        RuleFor(x => x.PhoneNumber).MaximumLength(20);

        ExtendRules();
    }

    private static string ResolveApiVersion(HttpContext? context, string defaultVersion)
    {
        if (context is null) return defaultVersion;
        if (context.Request.RouteValues.TryGetValue("version", out var rv) && rv is string rs && rs.Length > 0) return rs;
        if (context.Request.Headers.TryGetValue("api-version", out var hv) && hv.Count > 0) return hv[0] ?? defaultVersion;
        if (context.Request.Query.TryGetValue("api-version", out var qv) && qv.Count > 0) return qv[0] ?? defaultVersion;
        return defaultVersion;
    }

    private static bool IsAtLeast(string target, string current, string[] orderedVersions)
    {
        var ti = System.Array.IndexOf(orderedVersions, target);
        var ci = System.Array.IndexOf(orderedVersions, current);
        return ci >= 0 && ti >= 0 && ci >= ti;
    }

    /// <summary>
    /// Override this method to add custom validation rules beyond the auto-generated ones.
    /// </summary>
    protected virtual void ExtendRules() { }
}

#pragma warning restore CS0612 // Type or member is obsolete
#pragma warning restore CS1591 // Missing XML comment for publicly visible type or member
#pragma warning restore CS0618 // Type or member is obsolete
