// <auto-generated/>
// This file was auto-generated by @massivescale/tsp-aspnetcore-api. Do not edit manually.

#pragma warning disable CS1591 // Missing XML comment for publicly visible type or member
#pragma warning disable CS0612 // Type or member is obsolete
#pragma warning disable CS0618 // Type or member is obsolete
#nullable enable

using FluentValidation;
using Microsoft.AspNetCore.Http;

namespace MarketOnce.Community.Campaign.Api.Validators;

/// <summary>
/// Auto-generated version-aware PATCH validator for Store.
/// Each rule fires only when the corresponding property is present in the patch and
/// is conditioned on the API version resolved from the inbound HTTP request
/// (URL segment, <c>api-version</c> header, or <c>api-version</c> query parameter).
/// Extend this partial class to add custom validation rules.
/// </summary>
[System.Diagnostics.CodeAnalysis.ExcludeFromCodeCoverage]
public partial class StorePatchValidator : AbstractValidator<MarketOnce.Community.Campaign.Api.Helpers.MergePatch<MarketOnce.Community.Campaign.Api.Models.Store>>
{
    private static readonly string[] _versions = new[] { "v1.0", "v2.0" };

    /// <summary>
    /// Initializes a new instance of <see cref="StorePatchValidator"/> with version-aware auto-generated rules.
    /// </summary>
    public StorePatchValidator(IHttpContextAccessor httpContextAccessor)
    {
        var _apiVersion = ResolveApiVersion(httpContextAccessor.HttpContext, "v1.0");

        // Name must not be empty when provided
        this.RuleFor(x => x)
            .Must(x => (x.GetString("Name")?.Length ?? 0) > 0)
            .When(x => x.IsDefined("Name") && !x.IsNull("Name"))
            .WithName("Name");

        // Name cannot exceed a MaxLength of 100 when provided
        this.RuleFor(x => x)
            .Must(x => (x.GetString("Name")?.Length ?? 0) <= 100)
            .When(x => x.IsDefined("Name") && !x.IsNull("Name"))
            .WithName("Name");


        // PhoneNumber must not be empty when provided
        this.RuleFor(x => x)
            .Must(x => (x.GetString("PhoneNumber")?.Length ?? 0) > 0)
            .When(x => x.IsDefined("PhoneNumber") && !x.IsNull("PhoneNumber"))
            .WithName("PhoneNumber");



        // Rules added in v2.0
        When(_ => IsAtLeast("v2.0", _apiVersion, _versions), () =>
        {
            // Email must not be empty when provided
            this.RuleFor(x => x)
                .Must(x => (x.GetString("Email")?.Length ?? 0) > 0)
                .When(x => x.IsDefined("Email") && !x.IsNull("Email"))
                .WithName("Email");

            // Email cannot exceed a MaxLength of 255 when provided
            this.RuleFor(x => x)
                .Must(x => (x.GetString("Email")?.Length ?? 0) <= 255)
                .When(x => x.IsDefined("Email") && !x.IsNull("Email"))
                .WithName("Email");

            // Email must be a valid email address when provided
            this.RuleFor(x => x)
                .Must(x => System.Net.Mail.MailAddress.TryCreate(x.GetString("Email") ?? string.Empty, out _))
                .When(x => x.IsDefined("Email") && !x.IsNull("Email"))
                .WithName("Email");


        });

        ExtendRules();
    }

    private static string ResolveApiVersion(HttpContext? context, string defaultVersion)
    {
        if (context is null) return defaultVersion;
        if (context.Request.RouteValues.TryGetValue("version", out var rv) && rv is string rs && rs.Length > 0) return rs;
        if (context.Request.Headers.TryGetValue("api-version", out var hv) && hv.Count > 0) return hv[0] ?? defaultVersion;
        if (context.Request.Query.TryGetValue("api-version", out var qv) && qv.Count > 0) return qv[0] ?? defaultVersion;
        return defaultVersion;
    }

    private static bool IsAtLeast(string target, string current, string[] orderedVersions)
    {
        var ti = System.Array.IndexOf(orderedVersions, target);
        var ci = System.Array.IndexOf(orderedVersions, current);
        return ci >= 0 && ti >= 0 && ci >= ti;
    }

    /// <summary>
    /// Override this method to add custom validation rules beyond the auto-generated ones.
    /// </summary>
    protected virtual void ExtendRules() { }
}

#pragma warning restore CS0612 // Type or member is obsolete
#pragma warning restore CS1591 // Missing XML comment for publicly visible type or member
#pragma warning restore CS0618 // Type or member is obsolete
