// <auto-generated/>
// This file was auto-generated by @massivescale/tsp-aspnetcore-api. Do not edit manually.

#pragma warning disable CS1591 // Missing XML comment for publicly visible type or member
#pragma warning disable CS0612 // Type or member is obsolete
#pragma warning disable CS0618 // Type or member is obsolete
#nullable enable

using FluentValidation;
using Microsoft.AspNetCore.Http;

namespace MarketOnce.Community.Campaign.Api.Validators;

/// <summary>
/// Auto-generated version-aware POST validator for Store.
/// Rules are applied based on the API version resolved from the inbound HTTP request
/// (URL segment, <c>api-version</c> header, or <c>api-version</c> query parameter).
/// Extend this partial class to add custom validation rules.
/// </summary>
[System.Diagnostics.CodeAnalysis.ExcludeFromCodeCoverage]
public partial class StoreValidator : AbstractValidator<MarketOnce.Community.Campaign.Api.Models.Store>
{
    private static readonly string[] _versions = new[] { "v1.0", "v2.0" };

    /// <summary>
    /// Initializes a new instance of <see cref="StoreValidator"/> with version-aware auto-generated rules.
    /// </summary>
    public StoreValidator(IHttpContextAccessor httpContextAccessor, AbstractValidator<MarketOnce.Community.Campaign.Api.Models.Pet> petValidator)
    {
        var _apiVersion = ResolveApiVersion(httpContextAccessor.HttpContext, "v1.0");

        // Name is required
        RuleFor(x => x.Name).NotEmpty();

        // Name cannot exceed a MaxLength of 100
        RuleFor(x => x.Name).MaximumLength(100);

        // PhoneNumber is required
        RuleFor(x => x.PhoneNumber).NotEmpty();

        // Pets items are validated recursively
        RuleForEach(x => x.Pets).SetValidator(petValidator);

        // Rules added in v2.0
        When(_ => IsAtLeast("v2.0", _apiVersion, _versions), () =>
        {
            // Email is required
            RuleFor(x => x.Email).NotEmpty();

            // Email cannot exceed a MaxLength of 255
            RuleFor(x => x.Email).MaximumLength(255);

            // Email must be a valid email address
            RuleFor(x => x.Email).EmailAddress();

        });

        ExtendRules();
    }

    private static string ResolveApiVersion(HttpContext? context, string defaultVersion)
    {
        if (context is null) return defaultVersion;
        if (context.Request.RouteValues.TryGetValue("version", out var rv) && rv is string rs && rs.Length > 0) return rs;
        if (context.Request.Headers.TryGetValue("api-version", out var hv) && hv.Count > 0) return hv[0] ?? defaultVersion;
        if (context.Request.Query.TryGetValue("api-version", out var qv) && qv.Count > 0) return qv[0] ?? defaultVersion;
        return defaultVersion;
    }

    private static bool IsAtLeast(string target, string current, string[] orderedVersions)
    {
        var ti = System.Array.IndexOf(orderedVersions, target);
        var ci = System.Array.IndexOf(orderedVersions, current);
        return ci >= 0 && ti >= 0 && ci >= ti;
    }

    /// <summary>
    /// Override this method to add custom validation rules beyond the auto-generated ones.
    /// </summary>
    protected virtual void ExtendRules() { }
}

#pragma warning restore CS0612 // Type or member is obsolete
#pragma warning restore CS1591 // Missing XML comment for publicly visible type or member
#pragma warning restore CS0618 // Type or member is obsolete
