// <auto-generated/>
// This file was auto-generated by @massivescale/tsp-aspnetcore-api. Do not edit manually.

#pragma warning disable CS1591 // Missing XML comment for publicly visible type or member
#pragma warning disable CS0612 // Type or member is obsolete
#pragma warning disable CS0618 // Type or member is obsolete
#nullable enable

using FluentValidation;
using Microsoft.AspNetCore.Http;

namespace MarketOnce.Community.Campaign.Api.Validators;

/// <summary>
/// Auto-generated version-aware PATCH validator for Store.
/// Each rule fires only when the corresponding property is present in the patch and
/// is conditioned on the API version resolved from the inbound HTTP request
/// (URL segment, <c>api-version</c> header, or <c>api-version</c> query parameter).
/// Extend this partial class to add custom validation rules.
/// </summary>
[System.Diagnostics.CodeAnalysis.ExcludeFromCodeCoverage]
public partial class StorePatchValidator : AbstractValidator<MarketOnce.Community.Campaign.Api.Helpers.MergePatch<MarketOnce.Community.Campaign.Api.Models.Store>>
{
    private static readonly string[] _versions = new[] { "v1.0", "v2.0" };

    /// <summary>
    /// Initializes a new instance of <see cref="StorePatchValidator"/> with version-aware auto-generated rules.
    /// </summary>
        public StorePatchValidator(IHttpContextAccessor httpContextAccessor, AbstractValidator<MarketOnce.Community.Campaign.Api.Models.Pet> petValidator)
    {
        var _apiVersion = ResolveApiVersion(httpContextAccessor.HttpContext, "v1.0");

        // Name is required and cannot be removed
        this.RuleFor(x => x)
            .Must(x => !x.IsNull("Name"))
            .When(x => x.IsDefined("Name"))
            .WithName("Name")
            .WithMessage("'Name' is required and cannot be null.");

        // Name must not be empty when provided
        this.RuleFor(x => x)
            .Must(x => (x.GetString("Name")?.Length ?? 0) > 0)
            .When(x => x.IsDefined("Name") && !x.IsNull("Name"))
            .WithName("Name");

        // Name cannot exceed a MaxLength of 100 when provided
        this.RuleFor(x => x)
            .Must(x => (x.GetString("Name")?.Length ?? 0) <= 100)
            .When(x => x.IsDefined("Name") && !x.IsNull("Name"))
            .WithName("Name");

        // PhoneNumber is required and cannot be removed
        this.RuleFor(x => x)
            .Must(x => !x.IsNull("PhoneNumber"))
            .When(x => x.IsDefined("PhoneNumber"))
            .WithName("PhoneNumber")
            .WithMessage("'PhoneNumber' is required and cannot be null.");

        // PhoneNumber must not be empty when provided
        this.RuleFor(x => x)
            .Must(x => (x.GetString("PhoneNumber")?.Length ?? 0) > 0)
            .When(x => x.IsDefined("PhoneNumber") && !x.IsNull("PhoneNumber"))
            .WithName("PhoneNumber");

        // Pets is required and cannot be removed
        this.RuleFor(x => x)
            .Must(x => !x.IsNull("Pets"))
            .When(x => x.IsDefined("Pets"))
            .WithName("Pets")
            .WithMessage("'Pets' is required and cannot be null.");

                this.RuleFor(x => x).Custom((patch, context) =>
                {
                        if (!patch.Properties.TryGetValue("Pets", out var element) || element.ValueKind == System.Text.Json.JsonValueKind.Null) return;
                        if (element.ValueKind != System.Text.Json.JsonValueKind.Array)
                        {
                                context.AddFailure("Pets", "'Pets' must be an array.");
                                return;
                        }
                        var index = 0;
                        foreach (var item in element.EnumerateArray())
                        {
                                if (item.ValueKind != System.Text.Json.JsonValueKind.Object)
                                {
                                        context.AddFailure($"Pets[{index}]", "Array items must be objects.");
                                        index++;
                                        continue;
                                }
                                try
                                {
                                        var nestedModel = System.Text.Json.JsonSerializer.Deserialize<MarketOnce.Community.Campaign.Api.Models.Pet>(item.GetRawText());
                                        if (nestedModel is null)
                                        {
                                                context.AddFailure($"Pets[{index}]", "Array items must be objects.");
                                        }
                                        else
                                        {
                                                var nestedResult = petValidator.Validate(nestedModel);
                                                foreach (var failure in nestedResult.Errors)
                                                        context.AddFailure($"Pets[{index}].{failure.PropertyName}", failure.ErrorMessage);
                                        }
                                }
                                catch (System.Text.Json.JsonException)
                                {
                                        context.AddFailure($"Pets[{index}]", "The array item could not be deserialized.");
                                }
                                index++;
                        }
                });

        // Rules added in v2.0
        When(_ => IsAtLeast("v2.0", _apiVersion, _versions), () =>
        {
            // Email is required and cannot be removed
            this.RuleFor(x => x)
                .Must(x => !x.IsNull("Email"))
                .When(x => x.IsDefined("Email"))
                .WithName("Email")
                .WithMessage("'Email' is required and cannot be null.");

            // Email must not be empty when provided
            this.RuleFor(x => x)
                .Must(x => (x.GetString("Email")?.Length ?? 0) > 0)
                .When(x => x.IsDefined("Email") && !x.IsNull("Email"))
                .WithName("Email");

            // Email cannot exceed a MaxLength of 255 when provided
            this.RuleFor(x => x)
                .Must(x => (x.GetString("Email")?.Length ?? 0) <= 255)
                .When(x => x.IsDefined("Email") && !x.IsNull("Email"))
                .WithName("Email");

            // Email must be a valid email address when provided
            this.RuleFor(x => x)
                .Must(x => System.Net.Mail.MailAddress.TryCreate(x.GetString("Email") ?? string.Empty, out _))
                .When(x => x.IsDefined("Email") && !x.IsNull("Email"))
                .WithName("Email");

        });

        ExtendRules();
    }

    private static string ResolveApiVersion(HttpContext? context, string defaultVersion)
    {
        if (context is null) return defaultVersion;
        if (context.Request.RouteValues.TryGetValue("version", out var rv) && rv is string rs && rs.Length > 0) return rs;
        if (context.Request.Headers.TryGetValue("api-version", out var hv) && hv.Count > 0) return hv[0] ?? defaultVersion;
        if (context.Request.Query.TryGetValue("api-version", out var qv) && qv.Count > 0) return qv[0] ?? defaultVersion;
        return defaultVersion;
    }

    private static bool IsAtLeast(string target, string current, string[] orderedVersions)
    {
        var ti = System.Array.IndexOf(orderedVersions, target);
        var ci = System.Array.IndexOf(orderedVersions, current);
        return ci >= 0 && ti >= 0 && ci >= ti;
    }

    /// <summary>
    /// Implement this partial method in a hand-written part of this class to add custom
    /// validation rules beyond the auto-generated ones. When no implementation exists,
    /// the compiler removes both this declaration and the call to it.
    /// </summary>
    partial void ExtendRules();
}

#pragma warning restore CS0612 // Type or member is obsolete
#pragma warning restore CS1591 // Missing XML comment for publicly visible type or member
#pragma warning restore CS0618 // Type or member is obsolete
