// <auto-generated/>
// This file was auto-generated by @massivescale/tsp-aspnetcore-api. Do not edit manually.

#pragma warning disable CS1591 // Missing XML comment for publicly visible type or member
#pragma warning disable CS0612 // Type or member is obsolete
#pragma warning disable CS0618 // Type or member is obsolete
#nullable enable

using FluentValidation;
using Microsoft.Extensions.DependencyInjection;
using MarketOnce.Community.Campaign.Api.Models;
using MarketOnce.Community.Campaign.Api.Helpers;
using Microsoft.AspNetCore.Http;

namespace MarketOnce.Community.Campaign.Api.Validators;

/// <summary>
/// Extension methods for registering the auto-generated FluentValidation validators
/// with the ASP.NET Core dependency injection container.
/// </summary>
[System.Diagnostics.CodeAnalysis.ExcludeFromCodeCoverage]
public static class ValidatorsInitializer
{
    /// <summary>
    /// Registers all auto-generated FluentValidation validators.
    /// Each validator is registered as its concrete type, as <see cref="AbstractValidator{T}"/>
    /// (for cascade injection between validators), and as <see cref="IValidator{T}"/>
    /// (for the FluentValidation pipeline).
    /// <para>
    /// Version-aware validators require <see cref="IHttpContextAccessor"/>. Ensure
    /// <c>services.AddHttpContextAccessor()</c> has been called before this method.
    /// </para>
    /// </summary>
    [System.Diagnostics.CodeAnalysis.ExcludeFromCodeCoverage]
    public static IServiceCollection AddGeneratedValidators(this IServiceCollection services)
    {
        services.AddScoped<StoreValidator>();
        services.AddScoped<AbstractValidator<Store>>(sp => sp.GetRequiredService<StoreValidator>());
        services.AddScoped<IValidator<Store>>(sp => sp.GetRequiredService<StoreValidator>());

        services.AddScoped<StorePatchValidator>();
        services.AddScoped<AbstractValidator<MergePatch<Store>>>(sp => sp.GetRequiredService<StorePatchValidator>());
        services.AddScoped<IValidator<MergePatch<Store>>>(sp => sp.GetRequiredService<StorePatchValidator>());

        services.AddScoped<PetValidator>();
        services.AddScoped<AbstractValidator<Pet>>(sp => sp.GetRequiredService<PetValidator>());
        services.AddScoped<IValidator<Pet>>(sp => sp.GetRequiredService<PetValidator>());

        services.AddScoped<PetPatchValidator>();
        services.AddScoped<AbstractValidator<MergePatch<Pet>>>(sp => sp.GetRequiredService<PetPatchValidator>());
        services.AddScoped<IValidator<MergePatch<Pet>>>(sp => sp.GetRequiredService<PetPatchValidator>());

        services.AddScoped<TagValidator>();
        services.AddScoped<AbstractValidator<Tag>>(sp => sp.GetRequiredService<TagValidator>());
        services.AddScoped<IValidator<Tag>>(sp => sp.GetRequiredService<TagValidator>());

        services.AddScoped<CustomerValidator>();
        services.AddScoped<AbstractValidator<Customer>>(sp => sp.GetRequiredService<CustomerValidator>());
        services.AddScoped<IValidator<Customer>>(sp => sp.GetRequiredService<CustomerValidator>());

        services.AddScoped<CustomerPatchValidator>();
        services.AddScoped<AbstractValidator<MergePatch<Customer>>>(sp => sp.GetRequiredService<CustomerPatchValidator>());
        services.AddScoped<IValidator<MergePatch<Customer>>>(sp => sp.GetRequiredService<CustomerPatchValidator>());

        services.AddScoped<DogValidator>();
        services.AddScoped<AbstractValidator<Dog>>(sp => sp.GetRequiredService<DogValidator>());
        services.AddScoped<IValidator<Dog>>(sp => sp.GetRequiredService<DogValidator>());

        services.AddScoped<DogPatchValidator>();
        services.AddScoped<AbstractValidator<MergePatch<Dog>>>(sp => sp.GetRequiredService<DogPatchValidator>());
        services.AddScoped<IValidator<MergePatch<Dog>>>(sp => sp.GetRequiredService<DogPatchValidator>());

        services.AddScoped<CatValidator>();
        services.AddScoped<AbstractValidator<Cat>>(sp => sp.GetRequiredService<CatValidator>());
        services.AddScoped<IValidator<Cat>>(sp => sp.GetRequiredService<CatValidator>());

        services.AddScoped<CatPatchValidator>();
        services.AddScoped<AbstractValidator<MergePatch<Cat>>>(sp => sp.GetRequiredService<CatPatchValidator>());
        services.AddScoped<IValidator<MergePatch<Cat>>>(sp => sp.GetRequiredService<CatPatchValidator>());

        return services;
    }
}

#pragma warning restore CS0612 // Type or member is obsolete
#pragma warning restore CS1591 // Missing XML comment for publicly visible type or member
#pragma warning restore CS0618 // Type or member is obsolete
