//-----------------------------------------------------------------------
// <copyright file="WidgetsControllerBase.g.cs" />
//
// This file is AUTO-GENERATED. Do not edit this file directly.
// <auto-generated />
//-----------------------------------------------------------------------
#pragma warning disable CS1591 // Missing XML comment for publicly visible type or member
#pragma warning disable CS0612 // Type or member is obsolete
#nullable enable

using System;
using System.Collections.Generic;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;

namespace MassiveScale.Simple.Api.Example
{
    [ApiController]
    public abstract class WidgetsControllerBase : ControllerBase
    {
        /// <summary>
        /// List widgets
        /// </summary>
        [HttpGet("/api/widgets")]
        public abstract Task<IActionResult> List();

        /// <summary>
        /// Read widgets
        /// </summary>
        [HttpGet("/api/widgets/{id}")]
        public abstract Task<IActionResult> Read([FromRoute] string id);

        /// <summary>
        /// Create a widget
        /// </summary>
        [HttpPost("/api/widgets")]
        public abstract Task<IActionResult> Create([FromBody] Widget body);

        /// <summary>
        /// Update a widget
        /// </summary>
        [HttpPatch("/api/widgets/{id}")]
        public abstract Task<IActionResult> Update([FromRoute] string id, [FromBody] WidgetMergePatchUpdate body);

        /// <summary>
        /// Delete a widget
        /// </summary>
        [HttpDelete("/api/widgets/{id}")]
        public abstract Task<IActionResult> Delete([FromRoute] string id);

        /// <summary>
        /// Analyze a widget
        /// </summary>
        [HttpPost("/api/widgets/{id}/analyze")]
        public abstract Task<IActionResult> Analyze([FromRoute] string id);

    }

}

#pragma warning restore CS0612 // Type or member is obsolete
#pragma warning restore CS1591 // Missing XML comment for publicly visible type or member