/**
 * @module clean
 *
 * Removes previously-generated files from the emitter's output directories
 * before a fresh emit, so that renamed or deleted TypeSpec types do not leave
 * stale `.g.cs` files behind.
 *
 * The main export is {@link cleanOutputDirectories}, called by the emitter
 * before any file is written when `clean-output-dirs` is enabled (the default).
 *
 * ## Guardrails
 *
 * Cleaning is deliberately conservative — it must never delete hand-written
 * code that happens to live alongside generated files. A file is removed only
 * when **both** of the following hold:
 *
 * 1. Its name ends with the configured {@link ResolvedOptions.fileExtension}
 *    (default `.g.cs`), and
 * 2. Its contents carry the {@link GENERATED_MARKER} `<auto-generated` header
 *    written by the default `file` template.
 *
 * A file that matches the generated extension but lacks the marker is left in
 * place and reported via the `output-file-left-behind` warning — when in doubt,
 * the file is kept. Files that do not match the generated extension are ignored
 * silently, since they are plainly not emitter output.
 */

import { NoTarget, Program, resolvePath } from "@typespec/compiler";
import { ResolvedOptions } from "./emitter.js";
import { reportDiagnostic } from "./lib.js";

/**
 * Substring present in the header comment of every file emitted with the
 * default `file` template (`// <auto-generated />`). Used as the positive
 * confirmation that a file was produced by this emitter before it is deleted.
 *
 * The bare `<auto-generated` prefix matches all conventional spellings
 * (`<auto-generated/>`, `<auto-generated />`, `<auto-generated>`).
 */
const GENERATED_MARKER = "<auto-generated";

/**
 * Removes generated files from every configured output directory prior to
 * emitting. Directories are de-duplicated (models and interfaces share a
 * directory by default) and each is scanned recursively so that files placed in
 * namespace-derived sub-folders and per-version validator sub-directories are
 * also cleaned.
 *
 * Missing directories (e.g. on a first-ever emit) are skipped silently.
 *
 * @param program - The compiled TypeSpec program, whose host provides the file
 *   system used by `emitFile` (real or in-memory).
 * @param options - Resolved emitter options carrying the output directory paths
 *   and the generated file extension.
 */
export async function cleanOutputDirectories(
  program: Program,
  options: ResolvedOptions,
): Promise<void> {
  const dirs = new Set<string>([
    options.modelsOutputDir,
    options.interfacesOutputDir,
    options.controllersOutputDir,
    options.servicesOutputDir,
    options.helpersOutputDir,
    options.validatorsOutputDir,
  ]);

  for (const dir of dirs) {
    await cleanDirectory(program, dir, options);
  }
}

/**
 * Recursively scans a single directory, deleting confirmed generated files and
 * warning about extension-matching files that cannot be confirmed as generated.
 *
 * @param program - The compiled TypeSpec program (host + diagnostics).
 * @param dir - Absolute directory path to scan.
 * @param options - Resolved emitter options.
 */
async function cleanDirectory(
  program: Program,
  dir: string,
  options: ResolvedOptions,
): Promise<void> {
  let entries: string[];
  try {
    entries = await program.host.readDir(dir);
  } catch {
    // Directory does not exist yet (first emit) — nothing to clean.
    return;
  }

  for (const entry of entries) {
    const full = resolvePath(dir, entry);

    let isDirectory: boolean;
    try {
      isDirectory = (await program.host.stat(full)).isDirectory();
    } catch {
      continue;
    }

    if (isDirectory) {
      await cleanDirectory(program, full, options);
      continue;
    }

    // Only files that look like emitter output are ever candidates for
    // removal. Anything else (e.g. hand-written `.cs`) is left untouched.
    if (!entry.endsWith(options.fileExtension)) {
      continue;
    }

    if (await isGeneratedFile(program, full)) {
      await program.host.rm(full, { recursive: false });
    } else {
      // Looks generated by extension, but the marker is absent — keep it and
      // tell the user rather than risk deleting non-generated code.
      reportDiagnostic(program, {
        code: "output-file-left-behind",
        target: NoTarget,
        format: { path: full },
      });
    }
  }
}

/**
 * Reads a file and reports whether it carries the generated-code marker.
 * A read failure is treated as "not generated" so the file is preserved.
 *
 * @param program - The compiled TypeSpec program (host).
 * @param path - Absolute path to the candidate file.
 * @returns `true` only when the file content contains {@link GENERATED_MARKER}.
 */
async function isGeneratedFile(
  program: Program,
  path: string,
): Promise<boolean> {
  try {
    const file = await program.host.readFile(path);
    return file.text.includes(GENERATED_MARKER);
  } catch {
    return false;
  }
}
